services:
  web:
    image: contractclassification:1.0
    environment:
      - gpus=all
    network_mode: "host"
    container_name: contractclassification_standard
    volumes:
      - /mnt/data/htfldocker/data:/workspace/data
      - /mnt/data/roberta_wwm_ext:/workspace/roberta_wwm_ext
      - /mnt/data/htfl/model/bert:/workspace/model/bert/
    command: python3 torch_server.py -c config/bert_config.json -p 58080